channels:
  - nvidia
  - pytorch
  - anaconda
  - plotly
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipywidgets
  - jupyterlab_widgets
  - opencv
  - pillow
